<?php

namespace App\Http\Resources\v1;

use Illuminate\Http\Resources\Json\JsonResource;

class Article extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        //return parent::toArray($request);
        return [
            'title'=>$this->title,
            'time'=>$this->created_at,
            'user'=>$this->user->name
        ];
    }

    public function with($request)
    {
        //return parent::with($request); // TODO: Change the autogenerated stub
        return [
            'status'=>"ok",
        ];
    }
}
